version: '2'
services:
    samaauto-app:
        image: samaauto
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://samaauto-mysql:3306/samaauto?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    samaauto-mysql:
        extends:
            file: mysql.yml
            service: samaauto-mysql
